const shouldDisplayObject = () => {
  const shouldDisplay = {
    text: {
      required: true,
      label: true,
      note: true,
      limited: true,
      restricted: true,
      placeholder: false,
      scale: false,
      options: false,
      bg: false,
    },
    textarea: {
      required: true,
      label: true,
      note: false,
      limited: false,
      restricted: false,
      placeholder: true,
      scale: false,
      options: false,
      bg: false,
    },
    radio: {
      required: true,
      label: true,
      note: true,
      limited: false,
      restricted: false,
      placeholder: false,
      scale: false,
      options: true,
      bg: false,
    },
    rating2: {
      required: true,
      label: true,
      placeholder: false,
      note: false,
      limited: false,
      restricted: false,
      scale: true,
      options: true,
      bg: false,
    },
    rating5: {
      required: true,
      label: true,
      placeholder: false,
      note: false,
      limited: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    rating10: {
      required: true,
      label: true,
      note: false,
      limited: false,
      restricted: false,
      scale: false,
      options: true,
      placeholder: false,
      bg: false,
    },
    checkbox: {
      required: true,
      label: true,
      note: false,
      limited: false,
      restricted: false,
      placeholder: false,
      scale: false,
      options: true,
      bg: false,
    },
    select: {
      required: true,
      label: true,
      placeholder: false,
      note: false,
      limited: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    information: {
      required: false,
      label: false,
      placeholder: false,
      note: true,
      limited: false,
      restricted: false,
      scale: false,
      options: false,
      bg: true,
    },
  };
  return shouldDisplay;
};

export default shouldDisplayObject;
