const shouldDisplayObject = () => {
  const shouldDisplay = {
    text: {
      required: true,
      label: true,
      note: true,
      maxlength: true,
      restricted: true,
      scale: false,
      options: false,
      bg: false,
    },
    textarea: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: false,
      bg: false,
    },
    radio: {
      required: true,
      label: true,
      note: true,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    rating2: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: true,
      options: true,
      bg: false,
    },
    rating5: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    rating10: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    checkbox: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    select: {
      required: true,
      label: true,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: false,
    },
    information: {
      required: false,
      label: false,
      note: false,
      maxlength: false,
      restricted: false,
      scale: false,
      options: true,
      bg: true,
    },
  };
  return shouldDisplay;
};

export default shouldDisplayObject;
